apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  annotations:
    prometheus.io/scrape: 'true'
spec:
  ports:
  - port: 80
    nodePort: 8081
    targetPort: wordpress-port
    protocol: TCP
  selector:
    app: wordpress
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: wordpress
        track: stable
    spec:
      containers:
      - name: wordpress
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: wordpress-configmap
              key: wp_host
        - name: WORDPRESS_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: wordpress-configmap
              key: wp_database
        - name: WORDPRESS_DB_USER
          valueFrom:
            configMapKeyRef:
              name: wordpress-configmap
              key: wp_user
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
             secretKeyRef:
               name: database-password
               key: database_password
        ports:
        - containerPort: 80
          name: wordpress-port
