apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  annotations:
    prometheus.io/scrape: 'true'
spec:
  ports:
  - port: 80
    nodePort: 8081
    targetPort: wordpress-port
    protocol: TCP
  selector:
    app: wordpress
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: wordpress
        track: stable
    spec:
      containers:
      - name: wordpress
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 80
          name: wordpress-port
